### ISSUE TITLE
Data is not saved after restart.

### ISSUE THREAD

**Issue by zandercodes** [OkaeriPoland/fat-sentry#1]
Hello, I came across this project because I am also annoyed with Sentry and the many containers.
Unfortunately, all settings are reset after the restart.
Is there a way to save the settings?

**Comment by sandrwich** [comment]
Yes, this is DIND setup so as reommended in the readme you should create a [volume](https://docs.docker.com/storage/volumes/) or [host mount](https://docs.docker.com/storage/bind-mounts/) for `/var/lib/docker` inside your container: https://github.com/OkaeriPoland/fat-sentry#persistent-storage

**Comment by sandrwich** [comment]
Not expected any traction for this, but as we are here, I will extend the README with the instructions on persistence soon.

**Comment by sandrwich** [comment]
Seems like volume works as expected, but I'm seeing fails on a couple of containers inside after removal and recreation of fat-sentry container.

**Comment by sandrwich** [comment]
Got them! I wonder why have so much volumes when they already are binding a lot on `/sentry`..

```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "sentry-data",
                "Source": "/var/lib/docker/volumes/sentry-data/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/sentry/sentry",
                "Destination": "/etc/sentry",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sentry/geoip",
                "Destination": "/geoip",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sentry/certificates",
                "Destination": "/usr/local/share/ca-certificates",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```
```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/sentry/postgres",
                "Destination": "/opt/sentry",
                "Mode": "",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "sentry-postgres",
                "Source": "/var/lib/docker/volumes/sentry-postgres/_data",
                "Destination": "/var/lib/postgresql/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
 ```

~~Maybe there is no need for binding `/var/lib/docker` after all, and `/sentry` would do with some tweaking, but seems unlikely.~~

Yeah, not gonna happen. I think we need both.

```yml
    volumes:
      - "sentry-postgres:/var/lib/postgresql/data"
      - type: bind
        read_only: true
        source: ./postgres/
        target: /opt/sentry/
 ```
 
Looks like the specific location is from relative paths in the docker-compose.

**Comment by sandrwich** [comment]
I think it now works just fine with two binds. I'm going to close this, but let me know if it works for you. Also, if you don't mind, I would like to ask: where have you discovered the fat-sentry project?
